### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mordod** [gideonn/insta-Unfollow-Users#1]
as i try to run the code I get this error:
Token found...
Started Un-following
Traceback (most recent call last):
  File "<string>", line 132, in <module>
  File "<string>", line 45, in core
KeyError: 'data'
instaUnfollower returned -1
i'm not sure what to do for that.

**Comment by gideonn** [comment]
How does your config.txt file look like ?
Did you create the file as mentioned in readme file ?

The script was not able to extract your access token value.
Make sure that your config.txt file looks like below :-

access_token=token

**Comment by mordod** [comment]
my config.txt looks as such
access_token=####################
thanks for responding so quickly

**Comment by gideonn** [comment]
Remove that access_token value from here, keep it as your secret. Never share it with anyone else.

You're running the .exe ?

**Comment by mordod** [comment]
yes

**Comment by gideonn** [comment]
The other issue could be your access_token.

Post the below URL in your browser and tell me what you get (replace TOKEN with your actual token value) :
https://api.instagram.com/v1/users/self/follows?access_token=TOKEN&count=2

**Comment by mordod** [comment]
{"meta":{"error_type":"OAuthPermissionsException","code":400,"error_message":"This request requires scope=follower_list, but this access token is not authorized with this scope. The user must re-authorize your application with scope=follower_list to be granted this permissions."}}

**Comment by gideonn** [comment]
Your token isn't working, please follow the process again to generate a new token.

If your token was working, you'll see text in response.

**Comment by zlarsen** [comment]
I have a quick question, does your app have to not be a sandbox app? I am getting the same errors as @mordod

**Comment by gideonn** [comment]
No, this app will work fine for both sandbox and live. When you registered your client, you created an app in sandbox mode. The script has nothing to do with it and takes in the access_token.

Did you try getting new access_token ? Did it work ?

**Comment by zlarsen** [comment]
Yeah, I tried getting a new access_token and no dice. Sorry, not trying to be a pain in the butt or anything. Everything works for me on the instagram end, but when I try using your app I get traceback errors like @mordod .

**Comment by vickarma** [comment]
Hello, first of all thanks for your help.
I've been doing what you do, but it does not work.  Is this feature still working??
Thanks again!!
