### ISSUE TITLE
error

### ISSUE THREAD

**Issue by steffanjensen** [gideonn/insta-Unfollow-Users#2]
File "C:\Users\pc\Downloads\insta-Unfollow-Users-master\insta-Unfollow-Users-master\instaUnfollower.py", line 132, in <module>
    core()
  File "C:\Users\pc\Downloads\insta-Unfollow-Users-master\insta-Unfollow-Users-master\instaUnfollower.py", line 45, in core
    json_length = len(json_data['data'])
KeyError: 'data'

Why am i getting this error?

**Comment by Giando** [comment]
@reliefs probably at this address [https://api.instagram.com/v1/users/self/follows?access_token=123456789.1234567.0123456789abcdefghijklmnopqrstuv](https://api.instagram.com/v1/users/self/follows?access_token=123456789.1234567.0123456789abcdefghijklmnopqrstuv) (replacing the access_token with your) you will have your answer.

You should get something like this:

`{"meta": {"error_type": "OAuthPermissionsException", "code": 400, "error_message": "This request requires scope=follower_list, but this access token is not authorized with this scope. The user must re-authorize your application with scope=follower_list to be granted this permissions."}}`

I resolved sniffing the access_token from another application to 3rd parties! ;)

**Comment by julayjb** [comment]
Not working here. :(
error msg:

Token found...
Started Un-following
Traceback (most recent call last):
  File "<string>", line 132, in <module>
  File "<string>", line 45, in core
KeyError: 'data'
instaUnfollower returned -1

**Comment by jasetom** [comment]
@giando so if I get that message, how easy it is to add those permissions (scope=follower_list) to my access_token?

**Comment by zeinismalingga** [comment]
same problem with @julayjb

**Comment by gideonn** [comment]
Guys, you are getting the errors because Instagram changed its API behavior to not allow accessing someone else's data when the application is in sandbox mode.
As much as I want to publish the app in live mode, i can't, since it will not be approved.

I may plan to create a UI based app to do the same, publish it for review. 
But for now, this won't work.

**Comment by Giando** [comment]
Exactly, I have had the pleasure of using it for only 8 days, and **worked perfectly**. Then they changed the API and it was a mess.
Thanks anyway for all, @gideonn, you are Great!

**Comment by bilginunal** [comment]
You can solve your problem by visiting the site below:

https://api.instagram.com/oauth/authorize/?client_id=YOUR-CLIENT-ID&redirect_uri=YOUR-REDIRECT-URI&response_type=code&scope=follower_list

Change YOUR-CLIENT-ID with your client ID
Change YOUR-REDIRECT-URI with your registered redirect URI

for example

https://www.instagram.com/oauth/authorize/?client_id=a038XXXXXd7049XXX46f5XXXf4fffXXX&redirect_uri=http://www.google.com&response_type=code&scope=follower_list

It is working at the moment.
