### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by princebhalani143** [gideonn/insta-Unfollow-Users#6]
Hello Buddy,

I have tried and script is also accepting token and everything but when it's time to remove/unfollow user it's not performing anything I have same follower list. Can you please tell me how much time it'll take to unfollow? Even after pressing .exe file it's closing it automatically.

Thanks,
Prince

**Comment by gideonn** [comment]
I've added a note in README to inform everyone about the API changes. 
Stay tuned for updated.

Thanks!
